# Generated by Django 3.1 on 2020-08-25 13:00

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20200825_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether a paper is approved or not approved.', verbose_name='is_approved'),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Whether an order is confirmed that is can be done.', verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with this username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
